project_id = "zspmhkzosumopyfmlwvl"


[functions.sitemap]
verify_jwt = false

[functions.seed-products]
verify_jwt = false

[functions.steadfast-courier]
verify_jwt = false

[functions.meta-webhook]
verify_jwt = false


[functions.meta-capi]
verify_jwt = false
