project_id = "zspmhkzosumopyfmlwvl"

[functions.ai-seo-generate]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.seed-products]
verify_jwt = false

[functions.steadfast-courier]
verify_jwt = false
