/**
 * Order Service
 * Encapsulates all order-related database operations
 */

import { supabase } from "@/integrations/supabase/client";
import type { Order, OrderFilters, OrderStatus, PaymentStatus, ItemFulfillmentStatus } from "@/types/orders";
import type { Json } from "@/integrations/supabase/types";
import { PAGINATION } from "@/constants";

export interface OrderListResult {
  data: Order[];
  count: number;
}

export interface CreateOrderData {
  customer_id?: string | null;
  guest_email?: string | null;
  guest_phone?: string | null;
  shipping_name: string;
  shipping_phone: string;
  shipping_email?: string | null;
  shipping_address: string;
  shipping_city?: string | null;
  shipping_division_id?: string | null;
  shipping_thana_id?: string | null;
  shipping_postal_code?: string | null;
  payment_method_id?: string | null;
  payment_method_type?: "cod" | "mobile_banking" | "bank_transfer" | "card" | "online_gateway" | null;
  subtotal: number;
  discount_amount?: number;
  shipping_cost?: number;
  tax_amount?: number;
  total_amount: number;
  customer_notes?: string | null;
}

export interface CreateOrderItemData {
  order_id: string;
  product_id?: string | null;
  variant_id?: string | null;
  product_name: string;
  variant_sku?: string | null;
  variant_details?: Json;
  unit_price: number;
  quantity: number;
  line_total: number;
}

/**
 * Fetch paginated orders with optional filters
 */
export async function fetchOrders(
  filters: OrderFilters = {},
  page = 1,
  pageSize = PAGINATION.DEFAULT_PAGE_SIZE,
  signal?: AbortSignal
): Promise<OrderListResult> {
  const from = (page - 1) * pageSize;
  const to = from + pageSize - 1;

  let query = supabase
    .from("orders")
    .select(`
      *,
      customer:customers(id, name, phone, email),
      payment_method:payment_methods(id, name, type),
      items:order_items(
        id, product_name, variant_sku, variant_details,
        unit_price, quantity, line_total, fulfillment_status
      )
    `, { count: "exact" })
    .order("created_at", { ascending: false })
    .range(from, to);

  // Apply filters
  if (filters.status) {
    query = query.eq("order_status", filters.status);
  }
  if (filters.paymentStatus) {
    query = query.eq("payment_status", filters.paymentStatus);
  }
  if (filters.search) {
    query = query.or(
      `order_number.ilike.%${filters.search}%,shipping_name.ilike.%${filters.search}%,shipping_phone.ilike.%${filters.search}%`
    );
  }
  if (filters.dateFrom) {
    query = query.gte("created_at", filters.dateFrom);
  }
  if (filters.dateTo) {
    query = query.lte("created_at", filters.dateTo);
  }

  const { data, error, count } = await query.abortSignal(signal!);

  if (error) throw error;

  return {
    data: (data || []) as unknown as Order[],
    count: count || 0,
  };
}

/**
 * Fetch single order by ID
 */
export async function fetchOrderById(orderId: string): Promise<Order | null> {
  const { data, error } = await supabase
    .from("orders")
    .select(`
      *,
      customer:customers(id, name, phone, email, address, division_id, thana_id),
      payment_method:payment_methods(id, name, type, instructions),
      items:order_items(
        id, product_id, variant_id, product_name, variant_sku, variant_details,
        unit_price, quantity, line_total, fulfillment_status, fulfilled_quantity, returned_quantity
      ),
      shipping_division:divisions(id, name),
      shipping_thana:thanas(id, name)
    `)
    .eq("id", orderId)
    .single();

  if (error) throw error;

  return data as unknown as Order;
}

/**
 * Create a new order with items
 */
export async function createOrder(
  orderData: CreateOrderData,
  items: Omit<CreateOrderItemData, "order_id">[]
): Promise<Order> {
  // Insert order (order_number generated by trigger)
  const insertData = {
    order_number: "", // Will be overwritten by database trigger
    customer_id: orderData.customer_id,
    guest_email: orderData.guest_email,
    guest_phone: orderData.guest_phone,
    shipping_name: orderData.shipping_name,
    shipping_phone: orderData.shipping_phone,
    shipping_email: orderData.shipping_email,
    shipping_address: orderData.shipping_address,
    shipping_city: orderData.shipping_city,
    shipping_division_id: orderData.shipping_division_id,
    shipping_thana_id: orderData.shipping_thana_id,
    shipping_postal_code: orderData.shipping_postal_code,
    payment_method_id: orderData.payment_method_id,
    payment_method_type: orderData.payment_method_type,
    subtotal: orderData.subtotal,
    discount_amount: orderData.discount_amount ?? 0,
    shipping_cost: orderData.shipping_cost ?? 0,
    tax_amount: orderData.tax_amount ?? 0,
    total_amount: orderData.total_amount,
    customer_notes: orderData.customer_notes,
  };

  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert([insertData])
    .select()
    .single();

  if (orderError) throw orderError;

  // Insert order items with proper typing
  const orderItems = items.map((item) => ({
    order_id: order.id,
    product_id: item.product_id ?? null,
    variant_id: item.variant_id ?? null,
    product_name: item.product_name,
    variant_sku: item.variant_sku ?? null,
    variant_details: item.variant_details ?? null,
    unit_price: item.unit_price,
    quantity: item.quantity,
    line_total: item.line_total,
  }));

  const { error: itemsError } = await supabase
    .from("order_items")
    .insert(orderItems);

  if (itemsError) throw itemsError;

  // Fetch complete order with relations
  return fetchOrderById(order.id) as Promise<Order>;
}

/**
 * Update order status
 */
export async function updateOrderStatus(
  orderId: string,
  status: OrderStatus,
  notes?: string
): Promise<void> {
  const { data: order } = await supabase
    .from("orders")
    .select("order_status")
    .eq("id", orderId)
    .single();

  const previousStatus = order?.order_status;

  // Update order status
  const { error: updateError } = await supabase
    .from("orders")
    .update({
      order_status: status,
      ...(status === "shipped" && { shipped_at: new Date().toISOString() }),
      ...(status === "delivered" && { delivered_at: new Date().toISOString() }),
    })
    .eq("id", orderId);

  if (updateError) throw updateError;

  // Record status history
  await supabase.from("order_status_history").insert({
    order_id: orderId,
    status_type: "order",
    previous_status: previousStatus,
    new_status: status,
    notes,
  });
}

/**
 * Update payment status
 */
export async function updatePaymentStatus(
  orderId: string,
  status: PaymentStatus,
  notes?: string
): Promise<void> {
  const { data: order } = await supabase
    .from("orders")
    .select("payment_status")
    .eq("id", orderId)
    .single();

  const previousStatus = order?.payment_status;

  const { error: updateError } = await supabase
    .from("orders")
    .update({
      payment_status: status,
      ...(status === "paid" && { payment_verified_at: new Date().toISOString() }),
    })
    .eq("id", orderId);

  if (updateError) throw updateError;

  await supabase.from("order_status_history").insert({
    order_id: orderId,
    status_type: "payment",
    previous_status: previousStatus,
    new_status: status,
    notes,
  });
}

/**
 * Update item fulfillment status
 */
export async function updateItemFulfillment(
  itemId: string,
  status: ItemFulfillmentStatus,
  fulfilledQuantity?: number
): Promise<void> {
  const { error } = await supabase
    .from("order_items")
    .update({
      fulfillment_status: status,
      ...(fulfilledQuantity !== undefined && { fulfilled_quantity: fulfilledQuantity }),
    })
    .eq("id", itemId);

  if (error) throw error;
}

/**
 * Delete order with all related data
 */
export async function deleteOrder(orderId: string): Promise<void> {
  // Delete in correct order due to foreign key constraints
  await supabase.from("order_status_history").delete().eq("order_id", orderId);
  
  
  await supabase.from("order_items").delete().eq("order_id", orderId);

  const { error } = await supabase.from("orders").delete().eq("id", orderId);

  if (error) throw error;
}

/**
 * Fetch order status history
 */
export async function fetchOrderHistory(orderId: string) {
  const { data, error } = await supabase
    .from("order_status_history")
    .select("*")
    .eq("order_id", orderId)
    .order("created_at", { ascending: false })
    .limit(100);

  if (error) throw error;

  return data;
}
