// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.94.1";
import { z } from "npm:zod@^3.23.8";
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List active POSHPLEX products with images, variants, category, and brand. Supports pagination and optional category slug filter.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max products (default 50)"),
    offset: z.number().int().min(0).optional().describe("Pagination offset (default 0)"),
    category_slug: z.string().optional().describe("Filter by category slug")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, offset, category_slug }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    );
    const lim = Math.min(limit ?? 50, 200);
    const off = offset ?? 0;
    let query = supabase.from("products").select(
      `id, name, sku, base_price, product_type, is_featured,
         short_description, full_description, created_at,
         category:categories!inner(id, name, slug),
         brand:brands(id, name),
         images:product_images(image_url, is_main, sort_order),
         variants:product_variants(id, sku, selling_price, stock_quantity, image_url,
           color:colors(name, hex_code), size:sizes(label), material:materials(name))`,
      { count: "exact" }
    ).eq("is_active", true).order("created_at", { ascending: false }).range(off, off + lim - 1);
    if (category_slug) query = query.eq("category.slug", category_slug);
    const { data, count, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Found ${count ?? 0} products (returning ${data?.length ?? 0}).` }],
      structuredContent: { total: count ?? 0, limit: lim, offset: off, products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.94.1";
import { z as z2 } from "npm:zod@^3.23.8";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Get a single POSHPLEX product by its UUID, including all images and variants.",
  inputSchema: {
    id: z2.string().uuid().describe("Product UUID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    );
    const { data, error } = await supabase.from("products").select(
      `id, name, sku, base_price, product_type, is_active, is_featured,
         short_description, full_description, youtube_url, created_at, updated_at,
         category:categories(id, name, slug),
         brand:brands(id, name),
         images:product_images(id, image_url, thumb_url, medium_url, large_url, is_main, sort_order),
         variants:product_variants(id, sku, selling_price, stock_quantity, image_url,
           color:colors(id, name, hex_code),
           size:sizes(id, label),
           material:materials(id, name))`
    ).eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Product not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Product: ${data.name}` }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.94.1";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List all active POSHPLEX product categories with their slugs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    );
    const { data, error } = await supabase.from("categories").select("id, name, slug, description, image_url, sort_order").eq("is_active", true).order("sort_order", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} categories.` }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "poshplex-mcp",
  title: "POSHPLEX MCP",
  version: "0.1.0",
  instructions: "Read-only access to the POSHPLEX product catalog. Use `list_categories` to discover categories, `list_products` to browse (optionally filtering by category slug), and `get_product` to fetch full details for a single product by UUID.",
  tools: [list_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
